package automate.profit.autocoin.exchange.metadata


/**
 * Taken from https://support.kraken.com/hc/en-us/articles/360000767986-Cryptocurrency-withdrawal-fees-and-minimums
 *
 * According to https://docs.kraken.com/rest/#operation/getAssetInfo
 * Currenciec that kraken sends are available for deposit, withdrawal, trading and staking.
 */
val krakenOverridenCurrenciesMetadata: Map<String, CurrencyMetadataOverride> = mapOf(
    "ZRX" to CurrencyMetadataOverride(withdrawalFee = 12.0, minWithdrawalAmount = 24.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "1INCH" to CurrencyMetadataOverride(withdrawalFee = 5.0, minWithdrawalAmount = 10.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "AAVE" to CurrencyMetadataOverride(withdrawalFee = 0.05, minWithdrawalAmount = 0.12, isWithdrawalEnabled = true, isDepositEnabled = true),
    "GHST" to CurrencyMetadataOverride(withdrawalFee = 7.0, minWithdrawalAmount = 14.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "ALGO" to CurrencyMetadataOverride(withdrawalFee = 0.1, minWithdrawalAmount = 1.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "ANKR" to CurrencyMetadataOverride(withdrawalFee = 180.0, minWithdrawalAmount = 360.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "ANT" to CurrencyMetadataOverride(withdrawalFee = 3.0, minWithdrawalAmount = 4.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "REP" to CurrencyMetadataOverride(withdrawalFee = 0.75, minWithdrawalAmount = 1.5, isWithdrawalEnabled = true, isDepositEnabled = true),
    "REPV2" to CurrencyMetadataOverride(withdrawalFee = 0.75, minWithdrawalAmount = 1.5, isWithdrawalEnabled = true, isDepositEnabled = true),
    "AVAX" to CurrencyMetadataOverride(withdrawalFee = 0.05, minWithdrawalAmount = 0.5, isWithdrawalEnabled = true, isDepositEnabled = true),
    "AXS" to CurrencyMetadataOverride(withdrawalFee = 0.15, minWithdrawalAmount = 0.4, isWithdrawalEnabled = true, isDepositEnabled = true),
    "BADGER" to CurrencyMetadataOverride(withdrawalFee = 0.8, minWithdrawalAmount = 1.6, isWithdrawalEnabled = true, isDepositEnabled = true),
    "BAL" to CurrencyMetadataOverride(withdrawalFee = 0.7, minWithdrawalAmount = 0.8, isWithdrawalEnabled = true, isDepositEnabled = true),
    "BNT" to CurrencyMetadataOverride(withdrawalFee = 4.2, minWithdrawalAmount = 8.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "BAND" to CurrencyMetadataOverride(withdrawalFee = 3.0, minWithdrawalAmount = 7.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "BAT" to CurrencyMetadataOverride(withdrawalFee = 15.0, minWithdrawalAmount = 30.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "BNC" to CurrencyMetadataOverride(withdrawalFee = 0.5, minWithdrawalAmount = 1.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "BTC" to CurrencyMetadataOverride(withdrawalFee = 0.00002, minWithdrawalAmount = 0.0005, isWithdrawalEnabled = true, isDepositEnabled = true),
    "BCH" to CurrencyMetadataOverride(withdrawalFee = 0.0003, minWithdrawalAmount = 0.0006, isWithdrawalEnabled = true, isDepositEnabled = true),
    "ADA" to CurrencyMetadataOverride(withdrawalFee = 1.0, minWithdrawalAmount = 5.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "CTSI" to CurrencyMetadataOverride(withdrawalFee = 30.0, minWithdrawalAmount = 60.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "LINK" to CurrencyMetadataOverride(withdrawalFee = 0.7, minWithdrawalAmount = 1.5, isWithdrawalEnabled = true, isDepositEnabled = true),
    "CHZ" to CurrencyMetadataOverride(withdrawalFee = 80.0, minWithdrawalAmount = 160.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "COMP" to CurrencyMetadataOverride(withdrawalFee = 0.1, minWithdrawalAmount = 0.2, isWithdrawalEnabled = true, isDepositEnabled = true),
    "ATOM" to CurrencyMetadataOverride(withdrawalFee = 0.1, minWithdrawalAmount = 1.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "CQT" to CurrencyMetadataOverride(withdrawalFee = 25.0, minWithdrawalAmount = 50.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "CRV" to CurrencyMetadataOverride(withdrawalFee = 4.0, minWithdrawalAmount = 8.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "DASH" to CurrencyMetadataOverride(withdrawalFee = 0.005, minWithdrawalAmount = 0.01, isWithdrawalEnabled = true, isDepositEnabled = true),
    "DASH" to CurrencyMetadataOverride(withdrawalFee = 0.01, minWithdrawalAmount = 0.05, isWithdrawalEnabled = true, isDepositEnabled = true),
    "DAI" to CurrencyMetadataOverride(withdrawalFee = 15.0, minWithdrawalAmount = 30.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "MANA" to CurrencyMetadataOverride(withdrawalFee = 5.0, minWithdrawalAmount = 10.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "DOGE" to CurrencyMetadataOverride(withdrawalFee = 4.0, minWithdrawalAmount = 50.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "DYDX" to CurrencyMetadataOverride(withdrawalFee = 2.0, minWithdrawalAmount = 4.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "EWT" to CurrencyMetadataOverride(withdrawalFee = 0.26, minWithdrawalAmount = 1.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "ENJ" to CurrencyMetadataOverride(withdrawalFee = 6.0, minWithdrawalAmount = 12.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "MLN" to CurrencyMetadataOverride(withdrawalFee = 0.25, minWithdrawalAmount = 0.5, isWithdrawalEnabled = true, isDepositEnabled = true),
    "EOS " to CurrencyMetadataOverride(withdrawalFee = 0.05, minWithdrawalAmount = 0.5, isWithdrawalEnabled = true, isDepositEnabled = true),
    "ETH" to CurrencyMetadataOverride(withdrawalFee = 0.0035, minWithdrawalAmount = 0.005, isWithdrawalEnabled = true, isDepositEnabled = true),
    "ETC" to CurrencyMetadataOverride(withdrawalFee = 0.008, minWithdrawalAmount = 0.01, isWithdrawalEnabled = true, isDepositEnabled = true),
    "FIL" to CurrencyMetadataOverride(withdrawalFee = 0.01, minWithdrawalAmount = 0.1, isWithdrawalEnabled = true, isDepositEnabled = true),
    "FLOW" to CurrencyMetadataOverride(withdrawalFee = 0.03, minWithdrawalAmount = 1.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "GNO" to CurrencyMetadataOverride(withdrawalFee = 0.06, minWithdrawalAmount = 0.03, isWithdrawalEnabled = true, isDepositEnabled = true),
    "ICX" to CurrencyMetadataOverride(withdrawalFee = 10.0, minWithdrawalAmount = 20.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "INJ" to CurrencyMetadataOverride(withdrawalFee = 2.0, minWithdrawalAmount = 4.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "KAR" to CurrencyMetadataOverride(withdrawalFee = 1.0, minWithdrawalAmount = 2.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "KAVA" to CurrencyMetadataOverride(withdrawalFee = 0.15, minWithdrawalAmount = 1.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "KEEP" to CurrencyMetadataOverride(withdrawalFee = 18.0, minWithdrawalAmount = 36.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "KILT" to CurrencyMetadataOverride(withdrawalFee = 0.2, minWithdrawalAmount = 0.4, isWithdrawalEnabled = true, isDepositEnabled = true),
    "KINT" to CurrencyMetadataOverride(withdrawalFee = 0.1, minWithdrawalAmount = 0.2, isWithdrawalEnabled = true, isDepositEnabled = true),
    "KSM" to CurrencyMetadataOverride(withdrawalFee = 0.01, minWithdrawalAmount = 0.0105, isWithdrawalEnabled = true, isDepositEnabled = true),
    "KNC" to CurrencyMetadataOverride(withdrawalFee = 16.0, minWithdrawalAmount = 32.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "LSK" to CurrencyMetadataOverride(withdrawalFee = 0.3, minWithdrawalAmount = 1.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "LTC" to CurrencyMetadataOverride(withdrawalFee = 0.002, minWithdrawalAmount = 0.01, isWithdrawalEnabled = true, isDepositEnabled = true),
    "LPT" to CurrencyMetadataOverride(withdrawalFee = 0.6, minWithdrawalAmount = 1.6, isWithdrawalEnabled = true, isDepositEnabled = true),
    "LRC" to CurrencyMetadataOverride(withdrawalFee = 10.0, minWithdrawalAmount = 20.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "MKR" to CurrencyMetadataOverride(withdrawalFee = 0.0052, minWithdrawalAmount = 0.013, isWithdrawalEnabled = true, isDepositEnabled = true),
    "MINA" to CurrencyMetadataOverride(withdrawalFee = 0.05, minWithdrawalAmount = 1.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "MIR" to CurrencyMetadataOverride(withdrawalFee = 4.0, minWithdrawalAmount = 8.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "XMR" to CurrencyMetadataOverride(withdrawalFee = 0.0001, minWithdrawalAmount = 0.01, isWithdrawalEnabled = true, isDepositEnabled = true),
    "GLMR" to CurrencyMetadataOverride(withdrawalFee = 0.15, minWithdrawalAmount = 0.3, isWithdrawalEnabled = true, isDepositEnabled = true),
    "MOVR" to CurrencyMetadataOverride(withdrawalFee = 0.07, minWithdrawalAmount = 0.14, isWithdrawalEnabled = true, isDepositEnabled = true),
    "NANO" to CurrencyMetadataOverride(withdrawalFee = 0.05, minWithdrawalAmount = 0.1, isWithdrawalEnabled = true, isDepositEnabled = true),
    "OCEAN" to CurrencyMetadataOverride(withdrawalFee = 15.0, minWithdrawalAmount = 30.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "OMG" to CurrencyMetadataOverride(withdrawalFee = 3.0, minWithdrawalAmount = 6.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "OXT" to CurrencyMetadataOverride(withdrawalFee = 50.0, minWithdrawalAmount = 100.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "OGN" to CurrencyMetadataOverride(withdrawalFee = 25.0, minWithdrawalAmount = 50.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "OXY" to CurrencyMetadataOverride(withdrawalFee = 0.2, minWithdrawalAmount = 0.4, isWithdrawalEnabled = true, isDepositEnabled = true),
    "PAXG" to CurrencyMetadataOverride(withdrawalFee = 0.01, minWithdrawalAmount = 0.02, isWithdrawalEnabled = true, isDepositEnabled = true),
    "PERP" to CurrencyMetadataOverride(withdrawalFee = 2.0, minWithdrawalAmount = 4.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "PHA" to CurrencyMetadataOverride(withdrawalFee = 0.07, minWithdrawalAmount = 0.14, isWithdrawalEnabled = true, isDepositEnabled = true),
    "DOT" to CurrencyMetadataOverride(withdrawalFee = 0.05, minWithdrawalAmount = 1.05, isWithdrawalEnabled = true, isDepositEnabled = true),
    "MATIC" to CurrencyMetadataOverride(withdrawalFee = 15.0, minWithdrawalAmount = 30.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "QTUM" to CurrencyMetadataOverride(withdrawalFee = 0.01, minWithdrawalAmount = 0.1, isWithdrawalEnabled = true, isDepositEnabled = true),
    "RAY" to CurrencyMetadataOverride(withdrawalFee = 0.1, minWithdrawalAmount = 0.2, isWithdrawalEnabled = true, isDepositEnabled = true),
    "RARI" to CurrencyMetadataOverride(withdrawalFee = 1.0, minWithdrawalAmount = 2.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "REN" to CurrencyMetadataOverride(withdrawalFee = 30.0, minWithdrawalAmount = 60.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "XRP" to CurrencyMetadataOverride(withdrawalFee = 0.02, minWithdrawalAmount = 25.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "SRM" to CurrencyMetadataOverride(withdrawalFee = 0.1, minWithdrawalAmount = 0.2, isWithdrawalEnabled = true, isDepositEnabled = true),
    "SHIB" to CurrencyMetadataOverride(withdrawalFee = 373000.0, minWithdrawalAmount = 746000.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "SDN" to CurrencyMetadataOverride(withdrawalFee = 7.0, minWithdrawalAmount = 14.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "SC" to CurrencyMetadataOverride(withdrawalFee = 5.0, minWithdrawalAmount = 10.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "SOL" to CurrencyMetadataOverride(withdrawalFee = 0.01, minWithdrawalAmount = 0.02, isWithdrawalEnabled = true, isDepositEnabled = true),
    "XLM" to CurrencyMetadataOverride(withdrawalFee = 0.001, minWithdrawalAmount = 25.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "STORJ" to CurrencyMetadataOverride(withdrawalFee = 15.0, minWithdrawalAmount = 30.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "SUSHI" to CurrencyMetadataOverride(withdrawalFee = 1.5, minWithdrawalAmount = 4.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "SNX" to CurrencyMetadataOverride(withdrawalFee = 4.0, minWithdrawalAmount = 9.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "TBTC" to CurrencyMetadataOverride(withdrawalFee = 0.00015, minWithdrawalAmount = 0.0008, isWithdrawalEnabled = true, isDepositEnabled = true),
    "LUNA" to CurrencyMetadataOverride(withdrawalFee = 0.1, minWithdrawalAmount = 0.5, isWithdrawalEnabled = true, isDepositEnabled = true),
    "USDT " to CurrencyMetadataOverride(withdrawalFee = 15.0, minWithdrawalAmount = 20.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "USDT" to CurrencyMetadataOverride(withdrawalFee = 20.0, minWithdrawalAmount = 40.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "USDT" to CurrencyMetadataOverride(withdrawalFee = 2.5, minWithdrawalAmount = 5.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "XTZ" to CurrencyMetadataOverride(withdrawalFee = 0.4, minWithdrawalAmount = 0.8, isWithdrawalEnabled = true, isDepositEnabled = true),
    "GRT" to CurrencyMetadataOverride(withdrawalFee = 22.0, minWithdrawalAmount = 80.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "SAND" to CurrencyMetadataOverride(withdrawalFee = 3.0, minWithdrawalAmount = 6.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "TRX" to CurrencyMetadataOverride(withdrawalFee = 1.0, minWithdrawalAmount = 2.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "UNI" to CurrencyMetadataOverride(withdrawalFee = 0.6, minWithdrawalAmount = 1.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "USDC" to CurrencyMetadataOverride(withdrawalFee = 20.0, minWithdrawalAmount = 40.0, isWithdrawalEnabled = true, isDepositEnabled = true),
    "WAVES" to CurrencyMetadataOverride(withdrawalFee = 0.005, minWithdrawalAmount = 0.01, isWithdrawalEnabled = true, isDepositEnabled = true),
    "WBTC" to CurrencyMetadataOverride(withdrawalFee = 0.0005, minWithdrawalAmount = 0.001, isWithdrawalEnabled = true, isDepositEnabled = true),
    "YFI" to CurrencyMetadataOverride(withdrawalFee = 0.0007, minWithdrawalAmount = 0.0013, isWithdrawalEnabled = true, isDepositEnabled = true),
    "ZEC" to CurrencyMetadataOverride(withdrawalFee = 0.001, minWithdrawalAmount = 0.005, isWithdrawalEnabled = true, isDepositEnabled = true),
)
